# Generated by Django 3.2.7 on 2021-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210909_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=True, null=True, verbose_name='Sl.No'),
        ),
    ]
