# Generated by Django 3.2.7 on 2021-09-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='number',
        ),
    ]
