# Generated by Django 3.2.7 on 2021-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('heading', models.CharField(max_length=100, verbose_name='Video Heading')),
                ('video', models.FileField(upload_to='static/videos', verbose_name='Video')),
            ],
        ),
    ]
