# Generated by Django 3.2.7 on 2021-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/', verbose_name='Video'),
        ),
    ]
