# Generated by Django 3.2.7 on 2021-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fullname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
            ],
        ),
    ]
